### ISSUE TITLE
Azure Automation job gets suspended

### ISSUE THREAD

**Issue by Sabrthor** [microsoft/ARI#110]
I have setup an Automation Account and followed the [README](https://github.com/microsoft/ARI/blob/main/Automation/README.md) guide. I did testing on a Management group with single subscription and the report came out nicely. However, when I switch it to our production Management group which has a lot many subscriptions and underlying resources, the job gets suspended after running for a few minutes with exception message:

`The runbook job was attempted 3 times, but it failed each time.  Common reasons that runbook jobs fail can be found here:  https://docs.microsoft.com/en-us/azure/automation/automation-troubleshooting-automation-errors`

There were a lot of entries in the Error Field where each error retry refers to couple of variables $VNET and $SUBNET. I reviewed ARI_Automation.ps1, but couldn't find any reference of those two variables.

```
You cannot call a method on a null-valued expression. At line:45 char:17 + $VNET = $data.virtualNetworkSubnetId.split("/")[8] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (:) [], RuntimeException + FullyQualifiedErrorId : InvokeMethodOnNull
You cannot call a method on a null-valued expression. At line:46 char:17 + $SUBNET = $data.virtualNetworkSubnetId.split("/")[10] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (:) [], RuntimeException + FullyQualifiedErrorId : InvokeMethodOnNull
You cannot call a method on a null-valued expression. At line:45 char:17 + $VNET = $data.virtualNetworkSubnetId.split("/")[8] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (:) [], RuntimeException + FullyQualifiedErrorId : InvokeMethodOnNull
You cannot call a method on a null-valued expression. At line:46 char:17 + $SUBNET = $data.virtualNetworkSubnetId.split("/")[10] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (:) [], RuntimeException + FullyQualifiedErrorId : InvokeMethodOnNull
```

Seems like the offending script is: ARI/Modules/Compute/APPSERVICES.ps1.
Can someone please help me fix this?

**Comment by Claudio-Merola** [comment]
Hello,

The Automation Account method is outdated, we are working on a newer version.

To be honest I'm surprised it worked that far.

Do you have App Services in your environment? By the error message I believe it is complaining by empty values in that resource.

**Comment by Sabrthor** [comment]
Hello,

Yes, we indeed have quite a few App Services running in our environment. How do I go around this error message? Could you please advise?

**Comment by Claudio-Merola** [comment]
Hello,

Can you try the new automation account method we release in the version 3.0?

Thanks

**Comment by Sabrthor** [comment]
Hello @Claudio-Merola , the new script worked better than the previous one. I still see error messages in the job section, this makes me wonder did it pull out all the resources?

![Capture](https://github.com/microsoft/ARI/assets/21174359/54fb2101-3c19-404f-9f3f-984ff1f500c7)

Few of the messages from the Job streams:

`InvalidOperation: Line | 45 | $VNET = $data.virtualNetworkSubnetId.split("/")[8] | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | You cannot call a method on a null-valued expression.`

`InvalidOperation: Line | 46 | $SUBNET = $data.virtualNetworkSubnetId.split("/")[10] | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | You cannot call a method on a null-valued expression.`

`Remove-Variable: Line | 174 | … Remove-Variable PIP, vmnic, vmnsg, VNET, Subnet | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | Cannot find a variable with the name 'PIP'.`

`InvalidOperation: Line | 121 | … $PIP = $vmnic.properties.ipConfigurations.properties.publ … | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | You cannot call a method on a null-valued expression.`
Is there something I am doing differently?

**Comment by aizad02** [comment]
I believe the root cause of the automation script is due to this part.
![image](https://github.com/microsoft/ARI/assets/352502/7cfc5eb2-ddad-455b-bc79-bd4b72d3e9ee)

Invoke-WebRequest unable to get list url for the modules. Hence, causing a null error. (Nothing from the module list).
Been trying to filter but to no success. The list of *.ps1 files are lazy loaded as json result and populated using react.

**Comment by Claudio-Merola** [comment]
Hi @Sabrthor 

Last week I fixed a bug in the script that might have relation with your issue.

Can you try the updated version of the Automation Script and see how it goes?

Thanks

**Comment by Sabrthor** [comment]
Hi @Claudio-Merola,

Unfortunately, this still hasn't been solved.

I have done following:

1. Reinstalled all the required modules with Runtime 7.2.
2. Ensured the Automation Account has Reader permissions from the Management Group.
3. Ensured the Automation Account has Storage Blob Data Contributor permissions to the Storage Account.

When I ran the automation, the output still shows bunch of errors.
![image](https://github.com/microsoft/ARI/assets/21174359/e78a1f45-5402-4fed-a94f-ddbf6fa235e2)
![image](https://github.com/microsoft/ARI/assets/21174359/3a31f9c6-3c0a-4940-808f-e091797c863e)

What I could not believe is the difference in the resource list.

The spreadsheet shows a total resource count of 13004, whereas, I have about ~27k varied resources.

The same spreadsheet overview page says, I have 786 Virtual Machines in the Overview page:
![image](https://github.com/microsoft/ARI/assets/21174359/1f637607-de1c-410b-8aba-3d883f48563e)

The Virtual Machine sheet shows ~1400 machines:
![image](https://github.com/microsoft/ARI/assets/21174359/5a36c46a-1df1-446d-a16f-251a3e283e7f)

In the output of the Automation script, it says ~2200 VMs:
![image](https://github.com/microsoft/ARI/assets/21174359/3e972db4-9e02-4b98-9a90-1e2d22dda153)

While in reality, I have 1894 VMs. And this is just not limited to VMs, but almost any resource type (such as Virtual Network).

What I also observe is the Subscription list in the last sheet is completely wrong. I have about 40+ subscriptions and the sheet shows 24.

**Comment by Claudio-Merola** [comment]
Hi @Sabrthor ,

The Excel sheet will present more VMs, because of the extra resources, like VMs with more than 1 NIC, or the extensions, so is expected to have more lines. But the script should present the correct number of VMs...

I have updated the script some time ago with an extra option at the line 95, can you change the: $RunDebug to $true? So we can have some more details of might be going on.
